services:
    backend:
        build:
            context: .
            dockerfile: go/Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - .:/app
        environment:
            FRONT_URL: "http://localhost:3000"

    frontend:
        build:
            context: ./typescript/simple-mercari-web
        ports:
            - "3000:3000"
        volumes:
            - ./typescript/simple-mercari-web:/app
        environment:
            REACT_APP_API_URL: "http://localhost:9000"
