FROM golang:1.22.0-alpine

RUN addgroup -S mercari && adduser -S trainee -G mercari
# RUN chown -R trainee:mercari /path/to/db

WORKDIR /app

COPY . /app/
RUN mv db /db && chown -R trainee:mercari /db

WORKDIR /app/go

RUN go mod tidy

EXPOSE 9000
CMD ["go", "run", "app/main.go"]
