FROM golang:1.22.0-alpine

# install gcc and musl_dev
RUN apk add --no-cache gcc musl-dev

RUN addgroup -S mercari && adduser -S trainee -G mercari
# RUN chown -R trainee:mercari /path/to/db

WORKDIR /app

# copy only what is needed
COPY db/ ./db/
COPY go/ ./go/
COPY db/mercari.sqlite3 /app

RUN mv db /db && chown -R trainee:mercari /db

WORKDIR /app/go

RUN go mod tidy

EXPOSE 9000
CMD ["go", "run", "app/main.go"]
